# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobufs/node_messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobufs/node_messages.proto',
  package='chord',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1dprotobufs/node_messages.proto\x12\x05\x63hord\"\x1b\n\tSuccessor\x12\x0e\n\x06nodeId\x18\x01 \x01(\t'
)




_SUCCESSOR = _descriptor.Descriptor(
  name='Successor',
  full_name='chord.Successor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeId', full_name='chord.Successor.nodeId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['Successor'] = _SUCCESSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Successor = _reflection.GeneratedProtocolMessageType('Successor', (_message.Message,), {
  'DESCRIPTOR' : _SUCCESSOR,
  '__module__' : 'protobufs.node_messages_pb2'
  # @@protoc_insertion_point(class_scope:chord.Successor)
  })
_sym_db.RegisterMessage(Successor)


# @@protoc_insertion_point(module_scope)
